site_name: EVERSANA ETL Process Flow
site_url: https://BeleRohit.github.io/evr-docs/ # IMPORTANT: Update this URL!
site_description: A user-friendly guide to EVERSANA's ETL pipeline.
repo_url: https://github.com/BeleRohit/evr-docs
repo_name: evr-docs
edit_uri: edit/main/docs/ # Optional: Enable "Edit this page" links

# Theme configuration
theme:
  name: material
  logo: assets/images/eversana_logo.jpeg # Optional: Add a custom logo (replace with your path)
  favicon: assets/images/favicon.ico # Optional: Add a favicon

  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand # Expand active sections by default
    - navigation.top # Back-to-top button
    - toc.integrate
    - content.code.copy # Add copy buttons to code blocks
    - content.tabs.link
    - content.tooltips
    - content.action.edit # Show "Edit this page" link (if repo configured)
    - content.action.view # Show "View source" link
    - search.suggest
    - search.highlight
    - navigation.path # Show breadcrumb navigation

  icon:
    logo: material/factory
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Markdown Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

# Navigation structure
nav:
  - Home: index.md
  - Quick Reference:
      - Glossary: glossary.md
      - Metadata Tables: metadata_tables.md
  - Data Pipeline:
      - Overview: pipeline/overview.md
      - 3.1 Data Sources: pipeline/data_sources.md
      - 3.2 Ingestion & File Tracking: pipeline/ingestion_file_tracking.md
      - 3.3 Orchestration: pipeline/orchestration.md
      - 3.4 Data Processing: pipeline/data_processing.md
      - 3.5 Data Consumers: pipeline/data_consumers.md
  - Developer Guide:
      - 4. CI/CD Process: ci_cd.md
      - 7. How to Deploy Your Code: deployment_guide.md
  - Security & Monitoring:
      - 5. Security & Monitoring: security_monitoring.md

# Plugins
plugins:
  - search
  - git-revision-date-localized: # Shows "Last updated" on pages
      fallback_to_build_date: true
  - tags: # Optional, for future tagging of pages
  # - minify:
  #     minify_html: true

# Extra Configurations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BeleRohit/evr-docs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/eversana
  version:
    provider: mike # Optional if using versioning with mike

# Custom Directory for Docs (Optional)
docs_dir: docs

# Include static assets
extra_css:
  - assets/css/custom.css # Create for branding (optional)

extra_javascript:
  - assets/js/custom.js # For custom tooltips or behavior (optional)
